version: '3.8'

services:
  web:
    build:
      context: .
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done;
                      python3 manage.py makemigrations;
                      python3 manage.py migrate;
                      python manage.py loaddata fixtures/customer.json --app core.customer;
                      python manage.py loaddata fixtures/project.json --app core.project;
                      python manage.py loaddata fixtures/activity.json --app core.activity;
                      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data: