version: "3"

services:
  app:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"

    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - net
  db:
    image: postgres:10-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - net

volumes:
  pgdata:
networks:
  net: